# Generated by Django 5.1.5 on 2025-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
