# Generated by Django 5.1.5 on 2025-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_orderentry_is_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderentry",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderentry",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
