# Generated by Django 5.1.7 on 2025-03-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_orderentry_is_seen_alter_orderentry_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("qty", "Quantity"), ("container", "Container")],
                default="qty",
                max_length=20,
                null=True,
            ),
        ),
    ]
