# Generated by Django 5.1.5 on 2025-03-21 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_order_quantity_orderentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_quantity',
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('qty', 'Số lượng'), ('container', 'Container')], default='qty', max_length=20, null=True),
        ),
    ]
